# Generated by Django 5.1.6 on 2025-03-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=30)),
                ('author_last_name', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='book_image/')),
            ],
            options={
                'verbose_name': 'books',
            },
        ),
    ]
